### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by m1ga** [davrosull/ti-build-atom#4]
Hi, will you add Android support ('run on device')?

**Comment by davrosull** [comment]
Yep. Planning too - just haven't needed it yet so I've left it out for now!

From what I recall run on device gets a bit messy if you target one device so I might use the 'all' flag which will build the app to any device you have connected

**Comment by m1ga** [comment]
https://github.com/soulglo/ti-build-atom/pull/5

I've used your code and changed it a bit so it will push to a connected android device
